config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :pages
  devise_for :users

  #root 'profiles#index'

  devise_scope :user do
    authenticated :user do
      root 'profiles#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :profiles  do
    member do
      post 'update_quote'
    end

    resources :posts
    resources :activities do
      member do
        get 'like'
        get 'unlike'
        get 'shared'
      end
    end
  end

  resources :friends do
    collection do
      get 'pending'
    end
  end

  resources :after_register
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #     post :restore
  #     post :mark_as_read
  #   end
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  resources :messages
  resources :photos
  resources :albums
  resources :songs
  resources :conversations do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments] do
    member do
      get 'like'
      get 'unlike'
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :profile
  belongs_to :conversation
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @chosen_recipient = Profile.find_by(id: params[:to].to_i) if params[:to]
  end

  def index
    @chosen_recipient = Profile.find_by(id: params[:to].to_i) if params[:to]
  end

  # def create
  #   recipients = Profile.where(id: params['recipients'])
  #   conversation = current_profile.send_message(recipients, params[:message][:body], 'View').conversation
  #   flash[:success] = "Message has been sent!"
  #   redirect_to conversation_path(conversation)
  # end

  def create
    #binding.pry
    if @conversation = Conversation.between(current_profile.id, params[:receiver_id]).first
      #@conversation = Conversation.between(params[:sender_id],params[:receiver_id]).first
    else
     @conversation = Conversation.create!(sender_id: current_profile.id, receiver_id: params[:receiver_id])
    end

    Message.create!(body: params[:body], profile_id: current_profile.id, conversation_id: @conversation.id )
    redirect_to :back
  end

  private
  def message_params
    params.permit(:body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    Profile.all.each do |profile|
      s << "<option value='#{profile.id}'>#{profile.full_name}</option>"
    end
    s.html_safe
  end
end

app/views/messages/_new_modal.html.haml
#showMessage.modal.fade.bs-example-modal-lg{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Надіслати Повідомлення
      .modal-body
        = form_tag messages_path, method: :post do
          .form-group
            = label_tag 'body', 'Message'
            = text_area_tag 'body', nil, cols: 3, class: 'form-control', required: true
            = hidden_field_tag 'receiver_id', @profile.id
          / .form-group
          /   = label_tag 'recipients', 'Choose recipients'
          /   = select_tag('recipients', recipients_options(), multiple: true, class: 'form-control chosen-it')
          .form-group
            = submit_tag 'Надіслати', class: 'btn btn-primary'

app/views/messages/new.html.haml
- page_header "Start Conversation"
= form_tag messages_path, method: :post do
  .form-group
    = label_tag 'message[subject]', 'Subject'
    /= text_field_tag 'message[subject]', nil, class: 'form-control', required: true
  .form-group
    = label_tag 'message[body]', 'Message'
    = text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true
  .form-group
    = label_tag 'recipients', 'Choose recipients'
    = select_tag('recipients', recipients_options(), multiple: true, class: 'form-control chosen-it')
  .form-group
    = submit_tag 'Send', class: 'btn btn-primary'