config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :pages
  devise_for :users

  #root 'profiles#index'

  devise_scope :user do
    authenticated :user do
      root 'profiles#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :profiles  do
    member do
      post 'update_quote'
    end

    resources :posts
    resources :activities do
      member do
        get 'like'
        get 'unlike'
        get 'shared'
      end
    end
  end

  resources :friends do
    collection do
      get 'pending'
    end
  end

  resources :after_register
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #     post :restore
  #     post :mark_as_read
  #   end
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  resources :messages
  resources :photos
  resources :albums
  resources :songs
  resources :conversations do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments] do
    member do
      get 'like'
      get 'unlike'
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #acts_as_follower
  acts_as_liker
  #acts_as_messageable

  belongs_to :user
  has_many :albums
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :posts
  has_many :activities
  has_many :wall_activities, :foreign_key => "wall_id", :class_name => "Activity"
  has_many :shared_activities, :foreign_key => "shared_profile_id", :through => :activities
  has_many :profile_songs
  has_many :songs, through: :profile_songs
  has_many :profile_pages
  has_many :pages, through: :profile_pages
  has_many :profile_groups
  has_many :groups, through: :profile_groups

  mount_uploader :avatar, ImageUploader

  # Messages
  has_many :sent_conversations,     :class_name => 'Conversation', :foreign_key => 'sender_id'
  has_many :received_conversations, :class_name => 'Conversation', :foreign_key => 'receiver_id'

  has_many :friends_by_me, -> { where(status: 1) }, class_name: "Friend", foreign_key: "profile_id"
  has_many :friends_for_me, -> { where(status: 1) }, class_name: "Friend", foreign_key: "friend_id"
  has_many :friendships_by_me, through: :friends_by_me, source: :friend
  has_many :friendships_for_me, through: :friends_for_me, source: :profile

  has_many :pending_friends_by_me, -> { where(status: 0) }, class_name: "Friend", foreign_key: "profile_id"
  has_many :pending_friends_for_me, -> { where(status: 0) }, class_name: "Friend", foreign_key: "friend_id"
  has_many :pending_friendships_by_me, through: :pending_friends_by_me, source: :friend
  has_many :pending_friendships_for_me, through: :pending_friends_for_me, source: :profile

  accepts_nested_attributes_for :photos, allow_destroy: true

  def friends
    friends_by_me + friends_for_me
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def conversations
    sent_conversations + received_conversations
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :update_quote]

  def index
    @profiles = Profile.where.not(id: current_profile).page(params[:page]).per(5)
  end

  def show
    #@profile = Profile.find(params[:id])
    @activities = @profile.wall_activities.order('created_at DESC')
    @post= Post.new 
    #@post_images = @post.post_images.build
    @photos = @post.photos.build
    #@photo = @post_images.build_photo
  end

  def edit
    @profile.photos.build if @profile.photos.empty?
    #@profile = Profile.find(params[:id])
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Museum was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        #format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_quote
    @profile.update_attribute(:quote, params[:quote])
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:first_name, :avatar, :birthday, :last_name, :status, :terms_of_service, :city,
                                   photos_attributes: [:id, :image, :description])
    end
end

app/views/profiles/_contact.html.haml
.tab-pane.profile-section#contact
  %h2 Contact Information
  %p
    Where can we send you Brotherhood Swag and other packages? This is NOT shared with other Brothers.
  %hr
  /= render 'after_register/contact',  f: f

app/views/profiles/_form.html.haml
= simple_nested_form_for @profile, html: { novalidate: true, method: :put, class: 'form-vertical edit_brother', multipart: true }, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } } do |f|
  %ul.pager
    %li.pull-left
      = f.submit 'Save Changes', class: 'btn btn-primary btn-lg'
  %ul.nav.nav-tabs
    %li.active
      = link_to 'Personal Information', '#personal', data: { toggle: 'tab' }
    %li
      = link_to 'Contact Information', '#contact', data: { toggle: 'tab' }
    %li
      = link_to 'Social', '#social', data: { toggle: 'tab' }
    %li
      = link_to 'Life Outside of Business', '#passions', data: { toggle: 'tab' }
    %li
      = link_to 'Business Projects', '#photos', data: { toggle: 'tab' }


  .tab-content
    = render 'personal', f: f
    = render 'contact',  f: f
    /= render 'social',   f: f
    /= render 'passions',  f: f
    = render 'photos', f: f


    = f.submit 'Save Changes', class: 'btn btn-primary btn-lg'

app/views/profiles/_passions.html.haml
.tab-pane.profile-section#passions
  %h2 Life Outside of Business
  %p
    Your Brothers want to know what you're into
    %em outside
    of business.
  = render 'after_register/passions', f: f
  = render 'after_register/family', f: f
  = render 'after_register/brother_info', f: f

app/views/profiles/_personal.html.haml
.tab-pane.active.profile-section#personal
  %h2 Personal Information
  %br
  %br
  = render 'after_register/personal', f: f
  .row
    .col-sm-6
      .form-group
    /     %label.location-label Current Location
    /     %abbr.location-label{title: "required"} *
    /     = tag 'p', id: 'brother-locations', class: 'map-wraps map_container map-movable brothers-markers', data: { markers: @marker, styles: map_styles, zoom: 10, movable: true}
    /     .well.auto-location
    /       %label Auto-location is turned:
    /       %strong.locate-status
    /         - if @brother.auto_location
    /           On
    /         - else
    /           %span.red-font Off
    /       .pull-right
    /         %span.btn.btn-default.btn-sm.auto-locate Auto-Locate
    /       = f.hidden_field :auto_location
    /       %p
    /       %span.help-block.blue
    /         %strong
    /           If your location is not correct, please click on the map to correct it. Brothers will be reaching out to you based on your location.
    / .col-sm-6
    /   .row
    /     .col-xs-4
    /       = image_tag profile_photo, id: "brother_profile_photo_preview", class: 'img-circle profile-photo img-responsive'
    /     .col-sm-8
    /       = f.input :profile_photo, as: :file, required: true, input_html: { accept: "image/*" }
    /       %span.help-block
    /         %small.blue
    /           %strong Your profile photo must be a headshot of you. No group, cartoon, or distant photos, please. Your Brothers want to know what you look like!
    /       .progress.progress-striped.hidden
    /         .progress-bar.progress-bar-success{"aria-valuemax" => "100", "aria-valuemin" => "0", role: "progressbar", style: "width: 0%"}
    /           .percent 100%
    /       = f.hidden_field :remote_profile_photo_url
    /       = f.hidden_field :last_location, value: f.object.last_location_parametrized

app/views/profiles/_photos.html.haml
.tab-pane.profile-section#photos
  %h2
    Business Projects & Skills
  %p Your Brothers need to see your current AND past projects in order to be comfortable with bringing opportunities your way.
  /= render 'after_register/types_projects', f: f
  = f.fields_for :photos, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } } do |p|
    = p.input :image, label: 'Profile Photo', as: :file, input_html: { accept: "image/*"  }

//= f.link_to_add '+ Add a Project', :photos, class: 'btn btn-grey new'

app/views/profiles/_quote.html.haml
#Quote.modal.fade.bs-example-modal-lg{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Змінити Статус
      .modal-body
        = form_tag update_quote_profile_path(@profile) do
          .form-group
            = text_area_tag 'quote', @profile.quote, cols: 3, class: 'form-control', required: true
            = check_box_tag 'show_friend', 'yes'
    
          .form-group
            = submit_tag 'Надіслати', class: 'btn btn-primary'

app/views/profiles/_social.html.haml
.tab-pane.profile-section#social
  %h2 Social
  %p
    Where can your Brothers learn more about you?
  = render 'after_register/social', f: f

app/views/profiles/edit.html.haml
.container
  .row
    .col-xs-12
      %h1 Edit Your Profile
.container
  = render partial: 'form'

app/views/profiles/index.html.haml
%h1 Listing medics
//= text_field_tag "search", "", :autocomplete => "off", :id => "search"
/ = form_tag medics_path, method: :get, remote: true, class: 'form-horizontal ui-widget' do
/   .input-group
/     .col-sm-6= search_field_tag 'search', nil, placeholder: 'Search for Hangouts', required: true, class: 'form-control'
/     .col-sm-6= search_field_tag 'location', nil, placeholder: 'Search for Location', class: 'form-control'
/     %span.input-group-btn
/       %button.btn.btn-default Search
/ %ul#contact-results
%table
  %tr
    %th Title
    %th First name
    %th Last name
    %th Region
    %th City
    %th Category
    %th
    %th
    %th
  .medic
    - @profiles.each do |profile|
      %tr
        %td= profile.first_name
        %td= profile.last_name
        %td= link_to "Add Friend", friends_path(friend_id: profile), :method => :post 
%br
= paginate @profiles

app/views/profiles/new.html.haml
- add_breadcrumb :index, root_path
- add_breadcrumb 'Sign Up'

.title_wrap
  .container
    .row
      .col-md-10.col-sm-9.col-xs-8
        %h1 Sign Up

.container.content
  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'form-vertical' }) do |f|
    = f.error_notification
    = display_base_errors resource
    = f.input :first_name, required: true, autofocus: true
    = f.input :last_name, required: true
    = f.input :email, required: true
    = f.input :password, required: true
    = f.input :password_confirmation, required: true
    = f.button :submit, 'Sign up', class: 'btn-primary'
  = render 'devise/shared/links'

app/views/profiles/show.html.haml
.row.profile.page-container
  .col-xs-6
    .row
      .col-xs-5
        = image_tag ((@profile.avatar.present? ? @profile.avatar.url(:large) : "company_logo.png"))
      .col-xs-6
        %h4= @profile.full_name
        = @profile.quote
        %button.btn.-btn.-btn-ghost.-small.-main-color{"data-target" => "#Quote", "data-toggle" => "modal", :type => "button"}  Змінити
        /= best_in_place @profile, :quote, :as => :input, :nil => "Click me to add content!", :ok_button => 'Save', :cancel_button => 'Cancel'
        %table.table
          - if @profile.birthday.present?
            %tr
              %td День народження:
              %td= @profile.birthday.strftime("%d/%m/%Y")
          - if @profile.city.present?
            %tr
              %td Рiдне мiсто:
              %td= @profile.city
        %button.btn.-btn.-btn-ghost.-small.-main-color{"data-target" => "#showMessage", "data-toggle" => "modal", :type => "button"}  Надіслати Повідомлення
    .row.page-container
      .col-xs-10
        #paintings
        = simple_form_for([@profile, @post]) do |f|
          = f.input :body, label: false, placeholder: 'Що нового?'
          = hidden_field_tag 'photos_ids[]'
          = f.submit 'Post', class: "btn -btn -small btn-primary pull-right", id: 'post-submit'
          /= f.fields_for :post_images do |post_image|
          /= post_image.input :post_id
          / = f.fields_for :photos do |p|
          /   = p.input :image, as: :file, input_html: { multiple: true }
        = form_for(Photo.new) do |f|
          = f.file_field :image, multiple: true, name: "photo[image]"

        - @activities.each do |activity|
          .row
            .col-xs-2
              = image_tag ((activity.wall.avatar.present? ? activity.wall.avatar.url(:medium) : "company_logo.png"))
              - if activity.shared?
                = image_tag ((activity.profile.avatar.present? ? activity.profile.avatar.url(:medium) : "company_logo.png"))
            .col-xs-10.well
              = activity.item.andand.body
              %span.like-count-text= activity.count_likes
              %span.like-count-text= activity.count_shared

              /= link_to('Like', like_profile_activity_path(id: activity.id, profile_id: current_profile.id) )
              - if current_profile.likes?(activity)
                .like
                  = link_to('Unlike', unlike_profile_activity_path(id: activity.id, profile_id: current_profile.id) )
              - else
                .like{class: activity.id}
                  .unlike= link_to('Like', like_profile_activity_path(id: activity.id, profile_id: current_profile.id) )
              = link_to('Shared', shared_profile_activity_path(id: activity.id, profile_id: @profile.id) )
              = render partial: 'the_comments/tree', locals: { commentable: activity, comments_tree: activity.comments }
= render 'messages/new_modal'
= render 'profiles/quote'
%script#template-upload{:type => "text/x-tmpl"}
  :cdata
    <div class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
    </div>