config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :pages
  devise_for :users

  #root 'profiles#index'

  devise_scope :user do
    authenticated :user do
      root 'profiles#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :profiles  do
    member do
      post 'update_quote'
    end

    resources :posts
    resources :activities do
      member do
        get 'like'
        get 'unlike'
        get 'shared'
      end
    end
  end

  resources :friends do
    collection do
      get 'pending'
    end
  end

  resources :after_register
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #     post :restore
  #     post :mark_as_read
  #   end
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  resources :messages
  resources :photos
  resources :albums
  resources :songs
  resources :conversations do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments] do
    member do
      get 'like'
      get 'unlike'
    end
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => "sender_id", :class_name => 'Profile'
  belongs_to :receiver, :foreign_key => "receiver_id", :class_name => 'Profile'
  has_many :messages

  scope :between, -> (sender_id,receiver_id) do
    where("(sender_id = ? AND receiver_id  = ?) OR (sender_id = ? AND receiver_id  = ?)", sender_id,receiver_id, receiver_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  #before_action :get_conversation, except: [:index, :empty_trash]
  #before_action :get_box, only: [:index]

  def index
    @conversations = current_profile.conversations

  end

  def show
    @messages = load_conversation.messages
  end

  def mark_as_read
    @conversation.mark_as_read(current_profile)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    load_conversation
    Message.create(profile_id: current_profile.id, body: params[:body], conversation_id: @conversation.id)
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_profile)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_profile)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_profile).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_profile.mailbox
  end

  def load_conversation
    @conversation ||= Conversation.find(params[:id])
  end


  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.haml
%li.list-group-item.clearfix
  = link_to conversation.subject, conversation_path(conversation)
  .btn-group-vertical.pull-right
    - if conversation.is_trashed?(current_profile)
      = link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post
    - else
      = link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, |
        data: {confirm: 'Are you sure?'}                                                                           |
      - if conversation.is_unread?(current_profile)
        = link_to 'Mark as read', mark_as_read_conversation_path(conversation), |
          class: 'btn btn-xs btn-info', method: :post                           |
  %p= render 'conversations/participants', conversation: conversation
  %p
    = conversation.last_message.body
    %small
      (
      %span.text-muted>= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S")
      )

app/views/conversations/_participants.html.haml
- conversation.participants.each do |participant|
  - unless participant == current_profile
    = current_profile.full_name

app/views/conversations/index.html.haml
%h3 Your Conversations
%p= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary'
.row
  .col-sm-9
    - @conversations.each do |conversation|
      .row
        .col-sm-4= conversation.receiver.full_name
        .col-sm-6.text-left= conversation.messages.last.andand.body 
        .col-sm-2= link_to 'view',conversation
  / .col-sm-9
  /   - if @box == 'trash'
  /     %p= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, |
  /         data: {confirm: 'Are you sure?'}                                                                 |
  /   %ul.list-group= render partial: 'conversations/conversation', collection: @conversations
  /   = will_paginate

app/views/conversations/show.html.haml
%p
  Chatting with
  / \#{render 'conversations/participants', conversation: @conversation}
.panel.panel-default
  .panel-heading
  .panel-body
    .messages
      - @messages.each do |message|
        .media
          .col-sm-12= message.profile.full_name
          .col-sm-9= message.body
          .col-sm-3 says at #{message.created_at.strftime("%-d %B %Y, %H:%M:%S")}
           
= form_tag reply_conversation_path(@conversation), method: :post do
  .form-group
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true
  = submit_tag "Send Message", class: 'btn btn-primary'