config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :pages
  devise_for :users

  #root 'profiles#index'

  devise_scope :user do
    authenticated :user do
      root 'profiles#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :profiles  do
    member do
      post 'update_quote'
    end

    resources :posts
    resources :activities do
      member do
        get 'like'
        get 'unlike'
        get 'shared'
      end
    end
  end

  resources :friends do
    collection do
      get 'pending'
    end
  end

  resources :after_register
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
  #     post :reply
  #     post :restore
  #     post :mark_as_read
  #   end
  #   collection do
  #     delete :empty_trash
  #   end
  # end
  resources :messages
  resources :photos
  resources :albums
  resources :songs
  resources :conversations do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
  end
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments] do
    member do
      get 'like'
      get 'unlike'
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  include TheComments::Commentable
  acts_as_likeable
  acts_as_mentioner

  belongs_to :item, polymorphic: true
  belongs_to :profile
  belongs_to :wall, :foreign_key => "wall_id", :class_name => "Profile"
  has_many :shared_profiles, :foreign_key => "shared_activity_id", :class_name => "Share"

  #enum item_type: [:share, :post, :comment]

  def count_likes
    self.likers(Profile).length
  end

  def count_shared
    self.shared_profiles.length
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :privacy
  belongs_to :profile
  has_many :photos, as: :imageable, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include TheComments::Comment
  acts_as_likeable

  def count_likes
    self.likers(Profile).length
  end
  # ---------------------------------------------------
  # Define comment's avatar url
  # Usually we use Comment#user (owner of comment) to define avatar
  # @blog.comments.includes(:user) <= use includes(:user) to decrease queries count
  # comment#user.avatar_url
  # ---------------------------------------------------

  # public
  # ---------------------------------------------------
  # Simple way to define avatar url
  #
  # def avatar_url
  #   src = id.to_s
  #   src = title unless title.blank?
  #   src = contacts if !contacts.blank? && /@/ =~ contacts
  #   hash = Digest::MD5.hexdigest(src)
  #   "https://2.gravatar.com/avatar/#{hash}?s=42&d=https://identicons.github.com/#{hash}.png"
  # end
  # ---------------------------------------------------

  # private
  # ---------------------------------------------------
  # Define your content filters
  # gem 'RedCloth'
  # gem 'sanitize'
  # gem 'MySmilesProcessor'
  #
  # def prepare_content
  #   text = self.raw_content
  #   text = RedCloth.new(text).to_html
  #   text = MySmilesProcessor.new(text)
  #   text = Sanitize.clean(text, Sanitize::Config::RELAXED)
  #   self.content = text
  # end
  # ---------------------------------------------------
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => "sender_id", :class_name => 'Profile'
  belongs_to :receiver, :foreign_key => "receiver_id", :class_name => 'Profile'
  has_many :messages

  scope :between, -> (sender_id,receiver_id) do
    where("(sender_id = ? AND receiver_id  = ?) OR (sender_id = ? AND receiver_id  = ?)", sender_id,receiver_id, receiver_id, sender_id)
  end
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  enum status: [ :pending, :accept, :reject ]
  belongs_to :profile
  belongs_to :friend, class_name: 'Profile', foreign_key: 'friend_id'

  after_create :send_request
  def send_request
    #Notifier.friend_request(from, person).deliver
  end

  def update_accept
    self.update_attribute(:status, 'accept')
  end

  def update_reject
    self.update_attribute(:status, 'reject')
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :profile_groups
  has_many :profiles, through: :profile_groups
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :profile
  belongs_to :conversation
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :profile_pages
  has_many :profiles, through: :profile_pages
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  #belongs_to :album
  #belongs_to :profile
  has_many :post_images
  has_many :posts, through: :post_images

  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :profile
  belongs_to :wall, :foreign_key => "wall_id", :class_name => "Profile"
  has_many :post_images
  has_many :photos, through: :post_images

  accepts_nested_attributes_for :post_images
  accepts_nested_attributes_for :photos

  mount_uploader :avatar, ImageUploader

  after_create :create_activity

  def create_activity
    Activity.create(item: self, wall_id: wall_id, profile_id: profile_id)
  end
end

app/models/post_image.rb
class PostImage < ActiveRecord::Base
  belongs_to :photo
  belongs_to :post
  #accepts_nested_attributes_for :photo
end

app/models/privacy.rb
class Privacy < ActiveRecord::Base
  has_many :albums
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  #acts_as_follower
  acts_as_liker
  #acts_as_messageable

  belongs_to :user
  has_many :albums
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :posts
  has_many :activities
  has_many :wall_activities, :foreign_key => "wall_id", :class_name => "Activity"
  has_many :shared_activities, :foreign_key => "shared_profile_id", :through => :activities
  has_many :profile_songs
  has_many :songs, through: :profile_songs
  has_many :profile_pages
  has_many :pages, through: :profile_pages
  has_many :profile_groups
  has_many :groups, through: :profile_groups

  mount_uploader :avatar, ImageUploader

  # Messages
  has_many :sent_conversations,     :class_name => 'Conversation', :foreign_key => 'sender_id'
  has_many :received_conversations, :class_name => 'Conversation', :foreign_key => 'receiver_id'

  has_many :friends_by_me, -> { where(status: 1) }, class_name: "Friend", foreign_key: "profile_id"
  has_many :friends_for_me, -> { where(status: 1) }, class_name: "Friend", foreign_key: "friend_id"
  has_many :friendships_by_me, through: :friends_by_me, source: :friend
  has_many :friendships_for_me, through: :friends_for_me, source: :profile

  has_many :pending_friends_by_me, -> { where(status: 0) }, class_name: "Friend", foreign_key: "profile_id"
  has_many :pending_friends_for_me, -> { where(status: 0) }, class_name: "Friend", foreign_key: "friend_id"
  has_many :pending_friendships_by_me, through: :pending_friends_by_me, source: :friend
  has_many :pending_friendships_for_me, through: :pending_friends_for_me, source: :profile

  accepts_nested_attributes_for :photos, allow_destroy: true

  def friends
    friends_by_me + friends_for_me
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def conversations
    sent_conversations + received_conversations
  end
end

app/models/profile_page.rb
class ProfilePage < ActiveRecord::Base
  belongs_to :profile
  belongs_to :page
  #accepts_nested_attributes_for :photo
end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :shared_profile, :class_name => "Profile"
  belongs_to :shared_activity, :class_name => "Activity"
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :profile_songs
  has_many :profiles, through: :profile_songs

  mount_uploader :audio, AudioUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  include TheComments::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile, :dependent => :destroy

  after_create :build_profile

  def build_profile
    profile = Profile.new(user: self) # Associations must be defined correctly for this syntax, avoids using ID's directly.
  	profile.save(validate: false)
  end
end

app/views/layouts2/_favicons.haml
%link{ href: '/apple-touch-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152' }
%link{ href: '/favicon-196x196.png', rel: 'icon', sizes: '196x196', type: 'image/png' }
%link{ href: '/favicon-16x16.png', rel: 'icon', sizes: '16x16', type: 'image/png' }
%link{ href: '/favicon-32x32.png', rel: 'icon', sizes: '32x32', type: 'image/png' }

app/views/layouts2/_footer_links.haml
%ul.footer-links
  / %li.hidden-xs
  /   = link_to t('footer.powered_by'), 'http://church.io/', rel: 'nofollow'
  / %li= link_to t('footer.help'), page_for_public_path('help')
  / %li= link_to t('footer.privacy_policy'), page_for_public_path('help/privacy_policy')

app/views/layouts2/_navbar_right.haml
%ul.nav.navbar-nav
  %li.dropdown.tasks-menu
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      %i.glyphicon.glyphicon-user
      %span
        = current_user.profile.last_name
        %i.caret
    %ul.dropdown-menu
      %li.header
        = current_user.email
      %li
        = link_to current_user.profile do
          /= icon 'fa fa-user'
          = t('nav.profile_sub.show')
      / %li
      /   = link_to edit_person_path(@logged_in) do
      /     = icon 'fa fa-pencil'
      /     = t('nav.profile_sub.edit')
      / %li
      /   = link_to edit_person_account_path(@logged_in) do
      /     = icon 'fa fa-key'
      /     = t('nav.profile_sub.password')
      / %li
      /   = link_to edit_person_path(@logged_in, email: true) do
      /     = icon 'fa fa-envelope'
      /     = t('nav.profile_sub.email')
      / %li
      /   = link_to edit_person_privacy_path(@logged_in) do
      /     = icon 'fa fa-lock'
      /     = t('nav.profile_sub.privacy')
      / %li
      /   = link_to session_path, method: :delete do
      /     = icon 'fa fa-sign-out'
      /     = t("session.sign_out")

app/views/layouts2/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'UTF-8' }
    %title
      Bless
      - if @title.present?
        == | #{@title.gsub(/<.+?>/, '').html_safe}
    %meta{ content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', name: 'viewport' }
    = yield(:meta)
    = stylesheet_link_tag 'application'
    /= stylesheet_link_tag 'print', media: 'print'
    = yield(:css)
    = csrf_meta_tags
    = render partial: 'layouts/favicons'
    %link{ href: "//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic,400italic,600italic|Abel", rel: "stylesheet" }
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    = yield(:head)
    :javascript
      // prevent js links from firing before the rest of the js is loaded
      window.event_queue = [];
      document.addEventListener('click', function(e) {
        if (e.target.getAttribute('href') == '#' || e.target.getAttribute('data-toggle') == 'tab') {
          e.preventDefault();
          event_queue.push(e);
        }
      }, false);
  %body.skin-blue{ data: { 'datepicker-format' => 'datepicker_format' } }
    / header logo: style can be found in header.less
    %header.header
      = link_to 'Bless', root_path, class: 'logo'
      / Header Navbar: style can be found in header.less
      %nav.navbar.navbar-static-top{ role: "navigation" }
        / Sidebar toggle button
        %a.navbar-btn.sidebar-toggle{ 'data-toggle' => 'offcanvas', href: '#', role: 'button' }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-right
          = render 'layouts/navbar_right'
        %h3.site-name
          = link_to 'Bless', root_path
    .wrapper.row-offcanvas.row-offcanvas-left
      / Left side column. contains the logo and sidebar
      %aside.left-side.sidebar-offcanvas
        / sidebar: style can be found in sidebar.less
        %section.sidebar
          / Sidebar user panel
          / - if current_user
          /   .user-panel
          /     .pull-left.image
          /       = link_to @logged_in do
          /         = avatar_tag @logged_in, class: 'img-circle'
          /     .pull-left.info
          /       %p
          /         = t('nav.hello', person: link_to(@logged_in.first_name, @logged_in)).html_safe
          /       %a{href: "#"}
          /         %i.fa.fa-circle.text-success
          /         -# TODO
          /         Online
          / search form
          %form.sidebar-form{ action: '/search', method: 'get' }
            .input-group
              /= text_field_tag 'name', @search.try(:name), placeholder: t('search.form.name'), class: 'form-control'
              %span.input-group-btn
                %button#search-btn.btn.btn-flat{ name: 'seach', type: 'submit' }
                  %i.fa.fa-search
          / /.search form
          / sidebar menu: : style can be found in sidebar.less
          %ul.sidebar-menu
            / %li{ class: tab_selected?(:home) ? 'active' : '' }
            /   = link_to root_path do
            /     %i.fa.fa-home
            /     %span= t('nav.home')
            /     = new_stream_activity_badge(@logged_in)
            / %li{ class: tab_selected?(:profile) ? 'active' : '' }
            /   = link_to @person || @logged_in do
            /     %i.fa.fa-user
            /     %span= t('nav.profile')
            /     %i.fa.pull-right{ class: tab_expanded?(:profile) ? 'fa-angle-down' : 'fa-angle-left' }
            /   - if tab_expanded?(:profile)
            /     %ul.treeview-menu.visible
            /       %li
            /         = link_to edit_person_path(@person) do
            /           = icon 'fa fa-pencil'
            /           = t('nav.profile_sub.edit')
            /       %li
            /         = link_to edit_person_account_path(@person) do
            /           = icon 'fa fa-key'
            /           = t('nav.profile_sub.password')
            /       %li
            /         = link_to edit_person_path(@person, email: true) do
            /           = icon 'fa fa-envelope'
            /           = t('nav.profile_sub.email')
            /       %li
            /         = link_to edit_person_privacy_path(@person) do
            /           = icon 'fa fa-lock'
            /           = t('nav.profile_sub.privacy')
            /       - if @logged_in.admin?(:edit_profiles)
            /         %li
            /           = link_to person_relationships_path(@person) do
            /             = icon 'fa fa-link'
            /             = t('nav.profile_sub.relationships')
            / - if setting(:features, :groups)
            /   %li{ class: tab_selected?(:groups) ? 'active' : '' }
            /     = link_to groups_path do
            /       %i.fa.fa-group
            /       %span= t('nav.groups')
            /       = new_group_badge
            /       %i.fa.pull-right{ class: tab_expanded?(:groups) ? 'fa-angle-down' : 'fa-angle-left' }
            /     - if tab_expanded?(:groups)
            /       %ul.treeview-menu.visible
            /         - if @group.persisted?
            /           %li
            /             = link_to edit_group_path(@group) do
            /               = icon 'fa fa-pencil'
            /               = t('nav.groups_sub.edit')
            /         %li
            /           = link_to new_group_path do
            /             = icon 'fa fa-plus'
            /             = t('nav.groups_sub.new')
            / %li{ class: tab_selected?(:directory) ? 'active' : '' }
            /   = link_to search_path do
            /     %i.fa.fa-archive
            /     %span= t('nav.directory')
            /     %i.fa.pull-right{ class: tab_expanded?(:directory) ? 'fa-angle-down' : 'fa-angle-left' }
            /   - if tab_expanded?(:directory)
            /     %ul.treeview-menu.visible
            /       %li
            /         = link_to search_path(business: true) do
            /           = icon 'fa fa-briefcase'
            /           = t('nav.directory_sub.business')
            /       %li
            /         = link_to new_printable_directory_path do
            /           = icon 'fa fa-print'
            /           = t('nav.directory_sub.printed')
            /       %li
            /         = link_to search_path(advanced: true) do
            /           = icon 'fa fa-search'
            /           = t('nav.directory_sub.advanced')
            /       - if @logged_in.can_create?(Family)
            /         %li
            /           = link_to new_person_path do
            /             = icon 'fa fa-plus'
            /             = t('nav.directory_sub.new_person')
            / - if setting(:features, :documents)
            /   %li{ class: tab_selected?(:documents) ? 'active' : '' }
            /     = link_to documents_path do
            /       %i.fa.fa-file
            /       %span= t('nav.documents')
            / - if @logged_in.incomplete_tasks_count > 0
            /   %li{ class: tab_selected?(:tasks) ? 'active' : '' }
            /     = link_to tasks_path do
            /       %i.fa.fa-check-square
            /       %span= t('nav.tasks')
            /       = assigned_tasks_badge
            / - if @logged_in.admin?
            /   %li{ class: tab_selected?(:admin) ? 'active' : '' }
            /     = link_to admin_path do
            /       %i.fa.fa-cogs
            /       %span= t('nav.admin')
          = yield(:sidebar)
        / /.sidebar
      / Right side column. Contains the navbar and content of the page
      %aside.right-side
        - if header = yield(:header).presence
          = header
        - else
          %section.content-header
            /= breadcrumbs
            %h1
              = @title
              - if sub_title = yield(:sub_title).presence
                %small= sub_title
        %section.content
          /= flash_messages
          = yield
    .footer
      = render partial: 'layouts/footer_links'
    = javascript_include_tag 'application'
    = yield(:js)
    /= analytics_js

app/views/layouts2/signed_out.html.haml
!!!
%html{ class: "full-height #{@body_class}" }
  %head
    %meta{charset: "UTF-8"}
    %title
      = setting(:name, :site)
      - if @title.present?
        == | #{@title}
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}
    = yield(:meta)
    = stylesheet_link_tag 'application'
    = yield(:css)
    = csrf_meta_tags
    = render partial: 'layouts/favicons'
    %link{ href: "//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic,400italic,600italic|Abel", rel: "stylesheet" }
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    = yield(:head)
  %body{ class: @body_class || 'skin-blue' }
    %header.header
      = link_to setting(:name, :site), root_path, class: 'logo'
      %nav.navbar.navbar-static-top{role: "navigation"}
    %section{class: @section_class || 'content'}
      - content = yield
      - if content =~ /^\s*<div class=.row.>/m
        = flash_messages unless content =~ /class=.flash/
        - if @title
          %h2= @title
        = content
      - else
        .row
          .col-md-offset-3.col-md-6
            = flash_messages unless content =~ /class=.flash/
            - if title = yield(:title).presence
              = title
            - elsif @title and not @hide_title
              %h2= @title
            = content
    .footer
      = render partial: 'layouts/footer_links'
    = javascript_include_tag 'application'
    = yield(:js)

app/views/the_comments/_tree.html.erb
<%= render partial: "the_comments/#{TheComments.config.template_engine}/tree",
           locals: { commentable: commentable, comments_tree: comments_tree }
%>

app/views/the_comments/haml/_additional_info.html.haml
.additional_info{ style: "display:none" }
  %br
  %table.table.table-striped.table-hover
    %tr
      %th Tolerance time:
      %th IP:
      %th User Agent:
      %th Referer:
    %tr
      %td= comment.tolerance_time || :none
      %td= comment.ip
      %td= comment.user_agent
      %td= comment.referer

app/views/the_comments/haml/_comment.html.haml
= build_server_tree(tree, render_module: RenderCommentsTreeHelper, controller: controller)

app/views/the_comments/haml/_comment_body.html.haml
%table.comment_body.table.table-striped.table-hover
  %tr
    %td{ style: "width: 120px;"}
      %b= comment.commentable_type
      &rarr;
    %td
      = link_to comment.commentable_title, comment.commentable_url
      (#{comment.try(:commentable_state)})
  %tr
    %td
      %b= t('the_comments.title')
    %td= comment.title.blank? ? t('the_comments.guest_name') : comment.title
  %tr
    %td
      %b= t('the_comments.contacts')
    %td= comment.contacts
  %tr.success
    %td
      %b= t('the_comments.content')
    %td= comment.content

app/views/the_comments/haml/_comment_edit.html.haml
.edit_form{ style: "display:none" }
  = form_for comment, remote: true, html:{ role: :form } do |f|
    %table.table.table-striped.table-hover
      %tr{ style: "width: 100px;"}
        %td
          %b= comment.commentable_type
          &rarr;
        %td
          = link_to comment.commentable_title, comment.commentable_url
          (#{comment.try(:commentable_state)})
      %tr
        %td
          %b= t('the_comments.title')
        %td= f.text_field :title, class: "form-control"
      %tr
        %td
          %b= t('the_comments.contacts')
        %td= f.text_field :contacts, class: "form-control"
      %tr
        %td
          %b= t('the_comments.content')
        %td= f.text_area  :raw_content, class: "form-control", rows: 7
      %tr
        %td
        %td= f.submit t('the_comments.update'), class: "btn btn-success"
  %hr

app/views/the_comments/haml/_form.html.haml
%h3
  = link_to t('the_comments.new'), '#', id: :new_root_comment

= form_for Comment.new, remote: true, authenticity_token: true do |f|
  .error_notifier{ style: "display:none" }
  / %label= t('the_comments.form.title')
  / %p= f.text_field :title

  / %label= t('the_comments.form.contacts')
  / %p= f.text_field :contacts

  %label= t('the_comments.form.content')
  %p= f.text_area :raw_content

  %p.trap
    - TheComments.config.empty_inputs.each do |name|
      = text_field_tag name, nil, autocomplete: :off, tabindex: -1, id: nil
  
  = hidden_field_tag :tolerance_time, 0, id: nil, class: :tolerance_time

  = f.hidden_field :commentable_type, value: commentable.class
  = f.hidden_field :commentable_id,   value: commentable.id
  = f.hidden_field :parent_id, class: :parent_id

  %p
    = f.submit t('the_comments.form.create'), class: :btn

app/views/the_comments/haml/_manage_controls.html.haml
- hidden = "display:none"

.row.controls
  .col-md-9
    = link_to t('the_comments.edit'), "#", class: "edit btn btn-success"
    = link_to t('the_comments.cancel'), "#", class: "btn btn-warning edit", style: "display:none"

    - to_hide = comment.published? ? hidden : nil
    - opts    = { remote: true, style: to_hide, method: :post }
    = link_to [:to_published, comment], opts.merge(class: "btn btn-primary to_published") do
      = t('the_comments.to_published')
    
    - to_hide = comment.draft? ? hidden : nil
    - opts    = { remote: true, style: to_hide, method: :post }
    = link_to [:to_draft, comment], opts.merge(class: "btn btn-warning to_draft") do
      = t('the_comments.to_draft')

    - to_hide = comment.deleted? ? hidden : nil
    - opts    = { remote: true, style: to_hide, method: :delete, data: { confirm: t('the_comments.delete_confirm') } }
    = link_to [:to_deleted, comment], opts.merge(class: "btn btn-danger to_deleted") do
      = t('the_comments.to_deleted')

    - opts = { remote: true, method: :post}
    = link_to [:to_spam, comment], opts.merge(class: "btn btn-danger to_spam") do
      = t('the_comments.to_spam')
  .col-md-3.text-right
    = link_to t('the_comments.additional_info'), "#", class: "additional_info btn btn-info"

app/views/the_comments/haml/_sidebar.html.haml
- cuser = current_user

.panel.panel-primary
  .panel-heading= t "the_comments.nav.header"
  .panel-body
    %p= link_to raw(t('the_comments.back_to_root')), '/'
    %hr

    %h5= t 'the_comments.incoming'
    %ul
      %li= link_to t("the_comments.draft_comments",     num: cuser.draft_comcoms_count),     [:draft,     :comments]
      %li= link_to t("the_comments.published_comments", num: cuser.published_comcoms_count), [:published, :comments]
      %li= link_to t("the_comments.deleted_comments",   num: cuser.deleted_comcoms_count),   [:deleted,   :comments]
      %li= link_to t("the_comments.spam_comments",      num: cuser.spam_comcoms_count),      [:spam,      :comments]

    %h5= t 'the_comments.written_by_me'
    %ul
      %li= link_to t("the_comments.draft_comments",     num: cuser.my_draft_comments.count),     [:my_draft,     :comments]
      %li= link_to t("the_comments.published_comments", num: cuser.my_published_comments.count), [:my_published, :comments]
      %li= link_to t("the_comments.my_comments",        num: cuser.my_comments_count),           [:my_comments,  :comments]

    - if cuser.comments_admin?
      %h5= t 'the_comments.in_system'
      %ul
        %li= link_to t("the_comments.draft_comments",     num: Comment.with_state(:draft).count),     [:total_draft,     :comments]
        %li= link_to t("the_comments.published_comments", num: Comment.with_state(:published).count), [:total_published, :comments]
        %li= link_to t("the_comments.deleted_comments",   num: Comment.with_state(:deleted).count),   [:total_deleted,   :comments]
        %li= link_to t("the_comments.spam_comments",      num: Comment.where(spam: true).count),      [:total_spam,      :comments]

app/views/the_comments/haml/_tree.html.haml
.comments#comments
  %ol.comments_tree{ data: { comments: { tolarance_time: TheComments.config.tolerance_time  } } }
    = render partial: 'the_comments/haml/comment', locals: { tree: comments_tree }
  = render partial: 'the_comments/haml/form', locals: { commentable: commentable }

app/views/the_comments/haml/index.html.haml
- content_for :title do
  = t "the_comments.management"

- content_for :comments_sidebar do
  = render partial: 'the_comments/haml/sidebar'

- content_for :comments_main do
  = paginate @comments

  .comments
    - @comments.each do |comment|
      - klass = { published: :primary, draft: :warning, deleted: :danger }[comment.state.to_sym]
      .panel{ class: "panel-#{klass}" }
        .panel-heading= comment.title
        .panel-body
          = render partial: 'the_comments/haml/comment_body', locals: { comment: comment }

  = paginate @comments

app/views/the_comments/haml/manage.html.haml
- content_for :title do
  = t "the_comments.management"

- content_for :comments_sidebar do
  = render partial: 'the_comments/haml/sidebar'

- content_for :comments_main do
  = paginate @comments

  - if @comments.blank?
    .alert.alert-info= t 'the_comments.no_comments_here'

  .comments
    - @comments.each do |comment|
      - klass = { published: :primary, draft: :warning, deleted: :danger }[comment.state.to_sym]
      .panel{ class: "panel-#{klass}" }
        .panel-heading= comment.title
        .panel-body
          = render partial: 'the_comments/haml/comment_edit', locals: { comment: comment }
          = render partial: 'the_comments/haml/comment_body', locals: { comment: comment }

          = render partial: 'the_comments/haml/manage_controls', locals: { comment: comment }
          = render partial: 'the_comments/haml/additional_info', locals: { comment: comment }
        
  = paginate @comments